### ISSUE TITLE
Consolidated setup instructions

### ISSUE THREAD

**Issue by JayBazuzi** [VerifyTests/Verify.Avalonia#208]
As a novice, it took me a while to get the initial setup to work correctly. Once it worked I was able to condense the module-wide setup instructions to this file:

```
using System.Runtime.CompilerServices;
using Avalonia;
using Avalonia.Headless;
using Avalonia.Themes.Fluent;

[assembly: AvaloniaTestApplication(typeof(VerifyAvaloniaSetupApplication))]

public class VerifyAvaloniaSetupApplication : Application
{
    [ModuleInitializer]
    public static void Init() =>
        VerifyAvalonia.Initialize();

    public static AppBuilder BuildAvaloniaApp() =>
        AppBuilder.Configure<VerifyAvaloniaSetupApplication>()
            .UseSkia()
            .UseHeadless(new() { UseHeadlessDrawing = false });

    public VerifyAvaloniaSetupApplication()
    {
        this.Styles.Add(new FluentTheme());
    }
}
```

I think this would make initial adoption easier. If you agree, I would be willing to take a swing at a proper PR to implement this. Let me know.

**Comment by SimonCropp** [comment]
happy to accept a pr for this

tbh the docs are probably poor since i dont use this library

**Comment by JayBazuzi** [comment]
PR sent. I can see further opportunities for improvement but I was aiming for a bite-sized piece this time.
